# duel duration
countdown: 60

# allowed commmands in duel (without /)
allowed-commands: []

messages:
  bossbar-title: "CombatLog: {time}s"
  win: "You killed {player}"
  lose: "You were killed by {player}"
  command-blocked: "You cannot use commands during combat!"
