name: CombatLogPlugin
version: '1.0-SNAPSHOT'
main: com.antonk.combatlogplugin.CombatLogPlugin
api-version: '1.21'
permissions:
  combatlog.admin:
    description: Manage combat with /combatlog
    default: op
  combatlog.bypass:
    description: Commands are not blocked in combat
    default: op
